FROM postgres:11.4-alpine

#COPY init-hive-db.sh /docker-entrypoint-initdb.d/init-hive-db.sh  #  This line postgresql will run the script in the /docker-entrypoint-initdb.d/ directory when the container is started.

#RUN chmod +x /docker-entrypoint-initdb.d/init-hive-db.sh

EXPOSE 5432